Update release process (#1)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,30 +1,90 @@
+# Copyright 2025 The Authors (see AUTHORS file)
 #
-# TODO, WIP
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
 #
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
 name: 'terraform-linter'
 description: 'Lint Terraform configurations against the abcxyz style guide.'
 inputs:
   directory:
-    description: 'Directory with Terraform files to lint'
+    description: 'Directory to lint'
     default: '.'
+    deprecationMessage: 'Use "paths" input instead'
+  paths:
+    description: 'File or directory paths to lint'
+    default: '.'
+  version:
+    description: 'Version of terraform-linter to use'
+    default: 'latest'
 
 runs:
   using: 'composite'
   steps:
-    - id: 'checkout-pkg'
-      uses: 'actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b' # ratchet:actions/checkout@v4
-      with:
-        repository: 'abcxyz/pkg'
-        path: 'abcxyz-pkg'
-
-    - id: 'setup-go'
-      uses: 'actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7' # ratchet:actions/setup-go@v5
-      with:
-        go-version: '1.22'
-
-    - id: 'run-linter'
+    - id: 'download'
+      name: 'Download abcxyz/terraform-linter'
       shell: 'bash'
-      working-directory: 'abcxyz-pkg'
+      env:
+        VERSION: '${{ inputs.version }}'
       run: |-
-        go run ./cmd/terraform-linter ${GITHUB_WORKSPACE}/${{inputs.directory}}
+        # Create a unique output file outside of the checkout.
+        BINARY_PATH="${RUNNER_TEMP}/terraform-linter"
+
+        OS=""
+        if [[ "${RUNNER_OS}" == "Linux" ]]; then
+          OS="linux"
+        elif [[ "${RUNNER_OS}" == "macOS" ]]; then
+          OS="darwin"
+        elif [[ "${RUNNER_OS}" == "Windows" ]]; then
+          OS="windows"
+          BINARY_PATH="${BINARY_PATH}.exe"
+        else
+          echo "::error ::Unsupported operating system ${RUNNER_OS}"
+          exit 1
+        fi
+
+        ARCH=""
+        if [[ "${RUNNER_ARCH}" == "X64" ]]; then
+          ARCH="amd64"
+        elif [[ "${RUNNER_ARCH}" == "ARM64" ]]; then
+          ARCH="arm64"
+        else
+          echo "::error ::Unsupported system architecture ${RUNNER_ARCH}"
+          exit 1
+        fi
+
+        URL="https://github.com/abcxyz/terraform-linter/releases/download/${VERSION}/terraform-linter_${OS}_${ARCH}"
+        if [[ "${VERSION}" == "latest" ]]; then
+          URL="https://github.com/abcxyz/terraform-linter/releases/latest/download/terraform-linter_${OS}_${ARCH}"
+        fi
+
+        # Download the file, passing in authentication to get a higher rate limit
+        # limit: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
+        curl "${URL}" \
+          --silent \
+          --fail \
+          --location \
+          --header "Authorization: Token ${{ github.token }}" \
+          --output "${BINARY_PATH}"
+
+        # Mark as executable
+        chmod +x "${BINARY_PATH}"
+
+        # Save the result to an output.
+        echo "::notice::Downloaded binary to ${BINARY_PATH}"
+        echo "binary-path=${BINARY_PATH}" >> "${GITHUB_OUTPUT}"
+
+    - name: 'Run abcxyz/terraform-linter'
+      shell: 'bash'
+      env:
+        LINT_PATHS: '${{ inputs.directory || inputs.paths }}'
+      run: |-
+        ${{ steps.download.outputs.binary-path }} lint ${LINT_PATHS}
